### PR TITLE
WIP exposing booking as API endpoint

### PR DESCRIPTION
**Pull request by serroba**
This needs some refinement, testing and more. But is exposing bookings by date range. So is possible to do some basic tests. 

The endpoint is using the same level of authentication we have already in place.

### CODE REVIEW

**Comment by serroba** [comment]
@johnrivelt if you test this branch, you will see that is possible to get a collection of bookings, filtered by date and also `include` the publishers attached to a booking

simply do something like: `$.get('/api/bookings?from=2017-06-01T00:00:01Z&to=2017-07-01T00:00:01Z')` and you will get a collection of bookings. If you add `includes=publishers` you will get also the info from the publishers. If not, you will get a collection of ID for those publishers.

**Comment by serroba** [comment]
This is not ready, I did just some coding around, but I need to invest on some testing to validate what I am doing. I'd appreciate your feedback and some help doing maybe some code review on what I've done.

What do you think?

**Comment by johnrivelt** [comment]
Hi, @serroba ,

Just FYI, When I tried clone your forked branch and try to install with composer, it complained I am using PHP 7.0.0 :( 

I will move on to PHP 7.1.12 to test.

**Comment by johnrivelt** [comment]
Thank @serroba for your work.
I will count on you for the back-end.

**Comment by serroba** [comment]
oh really? I think this should depend only on php 7.0 Will review this, it shouldn't enforce 7.1. Thanks for letting me know about it.

**Comment by serroba** [comment]
Oh, you have merged already. I was planning to add a bit more validations. I will that shortly. I hope things are working. Will need to update the OAS file accordingly

**Pull request merged**
